### ISSUE TITLE
docker pull

### ISSUE THREAD

**Issue by GusakIurii** [kaack/elrs-joystick-control#12]
PS C:\WINDOWS\system32> docker pull oneeyefpv/windows-amd64-builder
Using default tag: latest
latest: Pulling from oneeyefpv/windows-amd64-builder
docker : a Windows version 10.0.20348-based image is incompatible with a 10.0.19045 host
строка:1 знак:1
+ docker pull oneeyefpv/windows-amd64-builder
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (a Windows versi...10.0.19045 host:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Can you share the compiled EXE file for Windows?

**Comment by kaack** [comment]
Hey, You can download the compiled exe for Windows on the releases page https://github.com/kaack/elrs-joystick-control/releases/tag/v0.2.1
