### ISSUE TITLE
How far can BetaFPV 1W Micro module be？

### ISSUE THREAD

**Issue by ZhouYixun** [kaack/elrs-joystick-control#3]
I have a BetaFPV 1W Micro module and Raspberry PI, and I plan to use this project. I wonder what the ideal distance is?

**Comment by kaack** [comment]
You can go pretty far on 1W with ELRS. Take a look over at https://www.expresslrs.org/info/long-range/#100mw . Several pilots have gone over 10KM on just 100mW.
