### ISSUE TITLE
RadioMaster Ranger Nano support

### ISSUE THREAD

**Issue by gemenerik** [kaack/elrs-joystick-control#8]
I managed to get this working on my HappyModel ES24TX-LITE over USB, but fail to do so on my RadioMaster Ranger Nano. I do not receive any packets back from the module. I can flash the module over USB just fine. The device has no DIP switch. I have already tried limiting the power of the module in the user defines. Power seems OK, no visible rebooting. Any pointers for what to investigate?

**Comment by gemenerik** [comment]
Got it to work by putting the RX pin on 3 and TX pin on 1. These appear unrelated to the backpack.

**Comment by brendanhpmullen** [comment]
Hello, tried Rx pin on 3 and TX on 1 and it didnt work for me. The LED light on the back of the external Ranger Nano module is still blinking orange at 1Hz after it boots once i connect the usb cable to it. The orange intermittent light means that no handset is detected? I'm guessing that that is why it is not binding? My Module and receiver are flashed with the same binding phrase.
